align.preset = more
assumeStandardLibraryStripMargin = true
danglingParentheses.preset = true
docstrings.removeEmpty = true
docstrings.style = SpaceAsterisk
maxColumn = 160
newlines.avoidForSimpleOverflow = [punct, slc]
project.git = true
rewrite.imports.expand = true
rewrite.rules = [AvoidInfix, Imports, PreferCurlyFors, RedundantParens, SortModifiers]
rewrite.trailingCommas.style = never
runner.dialect = scala212
version = 3.11.1
